services:
  php-apache:
    build: .
    container_name: php_apache_container
    ports:
      - "8080:80"  
    depends_on:
      - db         
    env_file:
      - .env       

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"  
    volumes:
      - ./sunglass_ecommerce.sql:/docker-entrypoint-initdb.d/sunglass_ecommerce.sql
      - mysql-data:/var/lib/mysql  # Persistent MySQL data

volumes:
  mysql-data:  

